### ISSUE TITLE
Create log import UI

### ISSUE THREAD

**Issue by carterv** [ShaneKent/PyEventLogViewer#30]
Create a UI for kicking off the log import process

**Comment by ShaneKent** [comment]
We will need to include a section for inputting an alias name for each of the event log files. This would allow us to import different event log files that have duplicates of the same record without getting confused on which file those records came from.

**Comment by ShaneKent** [comment]
From Bruce Pixley on 10/30/2017 12:22PM:

The event logs would have to be extracted from Volume Shadow Copy containers. For the purpose of this project, assume that they are EVTX files that are provided to you by the examiner. They just need to be injested like the other EVTX files.
 
Since you are looking at being able to bring in EVTX files from different machines/sources, you may want to consider allowing the person to provide an alias for each set of event logs.
 
For example, I have a computer that I am examining called SMITH. I extract the event logs from the default folder location and from the three Volume Shadow Copy containers (I will abbreviate as VSC1, VSC2, and VSC3)
 
Aliases: SMITH_PC, SMITH_VSC1, SMITH_VSC2, SMITH_VSC3, etc.
 
The output would display the alias field in a separate column.
 
You would definitely want to deduplicate as you will likely have 4 of the same event (one from each event log). However, if Smith cleared his event log prior to the analysis, the main event log may be missing records that are not recoverable. The VSC data version will hopefully still contain the events.

**Comment by ShaneKent** [comment]
@carterv I'm going to close this.

Please note the line in the previous comment: "The output would display the alias field in a separate column."

We will need to do this, not sure how you'd pull that data for each record if the alias is not stored in the record database.
