### ISSUE TITLE
Program wide settings

### ISSUE THREAD

**Issue by carterv** [ShaneKent/PyEventLogViewer#48]
I'm not sure how much of this is necessary, but the current code in util.data copies the latest version of the config in the package into the application directory if it doesn't already exist there. 

#47 requires the user to delete that copy if they want to grab the latest version of the config. 

It may be useful to add a UI for project-independent settings where the user can 'reset to default,' which would overwrite the application copy with the version in the package. Other configuration can be done here as well, such as editing the default colors for any project. 

This may be overkill. I'll leave it up to whoever grabs this ticket to decide what direction to take it in.

**Comment by ShaneKent** [comment]
@carterv Let's discuss this. We are already treating the config.json file inside of the local project directory as a program-wide type of settings file. This is apparent with the way that we are doing the 'startup-window' check.

I think it would be fine to close this issue because we already have the capabilities in place here.
